language: go
go: 1.x
dist: bionic

env:
  global:
    - SHFMT_URL=https://github.com/mvdan/sh/releases/download/v3.0.1/shfmt_v3.0.1_linux_amd64
    - GOFLAGS="-mod=readonly"

jobs:
  include:
    - name: Test
      before_script:
        - sudo apt-get install -y chromium-browser
        - go get github.com/agnivade/wasmbrowsertest@timeout
        - go get github.com/mattn/goveralls
      script: go test -run=TestWasm -v

addons:
  apt:
    update: true

cache:
  npm: true
  directories:
    - ~/.cache
    - ~/gopath/pkg
